### ISSUE TITLE
Cannot read property 'deoptValue' of undefined

### ISSUE THREAD

**Issue by Scrum** [boopathi/babel-minify#13]
i have a broken [build](https://travis-ci.org/GitScrum/postcss-attribute-selector-prefix/jobs/141527708) after update to v0.1.9

**Comment by boopathi** [comment]
Thanks!. Fixed it.. Will publish it later today.

The problem was the array / object pattern not being handled in variable deopt. There is some deopt happening in your code that re-declares a "var" using object or array pattern. I'll try to throw more warnings about this in later versions.

**Comment by Scrum** [comment]
@boopathi Thanks 👍

**Comment by Scrum** [comment]
@boopathi after update till 0.1.11 still the some error (

**Comment by boopathi** [comment]
Weird. Seems wrong.

I tried your code - https://github.com/GitScrum/postcss-attribute-selector-prefix/blob/master/src/index.js .. Seems to work fine. ... You can try it here - https://boopathi.in/babel-minify/ ...

**Comment by boopathi** [comment]
https://github.com/GitScrum/postcss-at-rules-variables/pull/87

looks like that is fixed... i'll add node 4 and 5 support soon...

**Comment by Scrum** [comment]
@boopathi Thanks, I'll wait for support node 4,5 👍
