### ISSUE TITLE
not applied babel plugins

### ISSUE THREAD

**Issue by Scrum** [boopathi/babel-minify#3]
Hi, i have problem when i transpiling es6 with using babel-preset-min and plugins babel-add-module-exports

src/index.js

``` js
export default (tree, a = {}) => {
    console.log(a, tree);
    return () => {};
};
```

babel config

``` json
"babel": {
    "presets": [
      "es2015",
      "min"
    ],
    "plugins": [
      "add-module-exports"
    ],
    "comments": true,
    "compact": true,
    "minified": true
  }
```

after run `$ babel src/ -d lib/` i get:

``` js
"use strict";Object.defineProperty(exports,"__esModule",{value:!0});exports.default=function(b){var c=arguments.length<=1||arguments[1]===void 0?{}:arguments[1];console.log(c,b);return function(){}};
```

_see in end line_

else run without presets `min` i get: 

``` js
"use strict";Object.defineProperty(exports,"__esModule",{value:true});exports.default=function(tree){var a=arguments.length<=1||arguments[1]===undefined?{}:arguments[1];console.log(a,tree);return function(){}};module.exports=exports["default"];
```

_see in end line_

**Comment by boopathi** [comment]
Thanks for reporting! Will take a look at it.

**Comment by boopathi** [comment]
The problem seems to be some plugin kinda overrides the Program_exit which add-module-exports uses. I'll try to detect it later. For now, try with `passPerPreset: true` in your babelrc and it should work fine.

**Comment by vigneshshanmugam** [comment]
https://github.com/boopathi/babel-minify/pull/4

**Comment by boopathi** [comment]
Just to clarify, if you're using babel-minify Node API or CLI, `passPerPreset` is true, and if you're using `babel-preset-min`, you have to manually set `passPerPreset` in your babelrc.

**Comment by Scrum** [comment]
@boopathi thanks  👍
